### ISSUE TITLE
dark mode example?

### ISSUE THREAD

**Issue by deadcoder0904** [danilowoz/create-content-loader#262]
im trying to find dark mode example on google but it doesn't understand my search query.

would love to see the colors used in dark mode if anyone has seen such in the wild?

**Comment by danilowoz** [comment]
Hey @deadcoder0904, thanks for raising this question.
Actually, this package doesn't have a way to "support" dark mode, because it doesn't aim to be environment-sensitive or something similar. However, it gives all props necessary to build your own loading with the colors and background and create a dark mode version in your end.

Here's an example:
https://codesandbox.io/s/darkmode-m34m4

Hope it helps

**Comment by deadcoder0904** [comment]
naah, i was asking about darkmode specific colors that actually look good for a content loader. found one:

```tsx
import { ReactChild } from 'react'
import { SkeletonTheme } from 'react-loading-skeleton'

interface ISkeletonDarkTheme {
	children: ReactChild
}

export const SkeletonDarkTheme = ({ children }: ISkeletonDarkTheme) => (
	<SkeletonTheme baseColor="#333" highlightColor="#666">
		{children}
	</SkeletonTheme>
)
```
